#ifndef RPGHELPER_MENUSH_H
#define RPGHELPER_MENUSH_H
void InitialMenu();
void TablesMenu();
void CreateTableMenu();
void EntryTableMenu();
void InTable();
void InSection();
#endif //RPGHELPER_MENUSH_H
